#!/usr/bin/env python3
"""
Generate src/assets-bundle.ts from files in /static.
This embeds all static assets as base64 in a TS module so we don't
depend on Cloudflare's [site] config (which can be flaky in dev).
"""
import base64
import json
import os
import sys

# Get the absolute path of the directory where this script is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Set paths relative to the script directory
STATIC_DIR = os.path.join(SCRIPT_DIR, '../static')
OUT_FILE = os.path.join(SCRIPT_DIR, '../src/assets-bundle.ts')

# text-based files
TEXT_EXTS = {'.css', '.js', '.json', '.html', '.svg', '.txt', '.xml'}
# binary files (encode as base64)
BINARY_EXTS = {'.png', '.jpg', '.jpeg', '.gif', '.ico', '.webp', '.woff', '.woff2', '.ttf'}


def main():
    if not os.path.isdir(STATIC_DIR):
        print(f'ERROR: {STATIC_DIR} not found', file=sys.stderr)
        sys.exit(1)

    assets = {}
    for name in sorted(os.listdir(STATIC_DIR)):
        path = os.path.join(STATIC_DIR, name)
        if not os.path.isfile(path):
            continue
        ext = os.path.splitext(name)[1].lower()
        with open(path, 'rb') as f:
            data = f.read()
        if ext in TEXT_EXTS:
            # store as utf-8 string
            try:
                text = data.decode('utf-8')
                assets[name] = {'content': text, 'encoding': 'utf-8'}
            except UnicodeDecodeError:
                assets[name] = {'content': base64.b64encode(data).decode('ascii'), 'encoding': 'base64'}
        elif ext in BINARY_EXTS:
            assets[name] = {'content': base64.b64encode(data).decode('ascii'), 'encoding': 'base64'}
        else:
            # default to base64
            assets[name] = {'content': base64.b64encode(data).decode('ascii'), 'encoding': 'base64'}

    # generate TS file
    # برای جلوگیری از مشکل quote-escaping، از JSON.stringify استفاده می‌کنیم
    json_str = json.dumps(assets, ensure_ascii=False, indent=2)

    ts_code = f'''// AUTO-GENERATED — do not edit manually
// Generated by scripts/gen_assets.py from /static

export const ASSETS: Record<string, {{ content: string; encoding: 'utf-8' | 'base64' }}> = {json_str};
'''

    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write(ts_code)

    size = os.path.getsize(OUT_FILE)
    print(f'✓ Generated {OUT_FILE} ({size:,} bytes, {len(assets)} assets)')
    for name, asset in assets.items():
        print(f'  - {name}: {len(asset["content"]):,} chars ({asset["encoding"]})')


if __name__ == '__main__':
    main()
